### ISSUE TITLE
Move work experience to the top

### ISSUE THREAD

**Issue by Twoos123** [Twoos123/asadali-portfolio#9]

**Comment by MFarabi619** [comment]
Remove this, not really relevant and doesn't differentiate you. It's also not experience.

![Image](https://github.com/Twoos123/asadali-portfolio/assets/54924158/c4e1e3d6-9dd8-42d7-9d87-0e8b8cc596e0)

Also just a UX thing, the title already says University of Ottawa. Your users can infer that it's probably located in Ottawa, so no need to mention the location again.

For the Fuze card, rather than having the location as text, see if you can make it an icon pin on the corner or something.
